/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#e8e8e8',
        'tertiary-container': '#b2b3b3',
        'primary-container': '#d4af37',
        'primary-fixed-dim': '#e9c349',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#574500',
        'on-primary-fixed': '#241a00',
        'on-primary': '#ffffff',
        'surface-tint': '#735c00',
        'secondary-container': '#e2e2e2',
        'surface-variant': '#e2e2e2',
        outline: '#7f7663',
        background: '#ffffff',
        'on-tertiary-fixed-variant': '#454747',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#646464',
        primary: '#735c00',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#c6c6c7',
        'outline-variant': '#d0c5af',
        'tertiary-fixed': '#e2e2e2',
        surface: '#ffffff',
        'surface-container-low': '#f3f3f3',
        'on-tertiary-container': '#434546',
        'on-secondary-fixed': '#1b1b1b',
        error: '#ba1a1a',
        'inverse-primary': '#e9c349',
        'on-surface-variant': '#4d4635',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e2e2e2',
        'surface-container': '#eeeeee',
        'on-tertiary-fixed': '#1a1c1c',
        'surface-bright': '#f9f9f9',
        'inverse-on-surface': '#f1f1f1',
        'inverse-surface': '#2f3131',
        'primary-fixed': '#ffe088',
        secondary: '#5e5e5e',
        'on-surface': '#1a1c1c',
        'secondary-fixed-dim': '#c6c6c6',
        'on-primary-container': '#554300',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#474747',
        'surface-dim': '#dadada',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#e2e2e2',
        tertiary: '#5d5f5f',
        'on-background': '#1a1c1c',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'container-max': '1280px',
        gutter: '24px',
        unit: '4px',
        'margin-desktop': '80px',
      },
      fontFamily: {
        'headline-md': ['Plus Jakarta Sans'],
        'display-lg-mobile': ['Plus Jakarta Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'badge-txt': ['Inter'],
        'body-lg': ['Plus Jakarta Sans'],
        'label-sm': ['JetBrains Mono'],
        'body-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'badge-txt': ['11px', { lineHeight: '12px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
