/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background:                  'var(--color-background)',
        surface:                     'var(--color-surface)',
        'surface-bright':            'var(--color-surface-bright)',
        'surface-dim':               'var(--color-surface-dim)',
        'surface-variant':           'var(--color-surface-variant)',
        'surface-container-lowest':  'var(--color-surface-container-lowest)',
        'surface-container-low':     'var(--color-surface-container-low)',
        'surface-container':         'var(--color-surface-container)',
        'surface-container-high':    'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-background':             'var(--color-on-background)',
        'on-surface':                'var(--color-on-surface)',
        'on-surface-variant':        'var(--color-on-surface-variant)',
        outline:                     'var(--color-outline)',
        'outline-variant':           'var(--color-outline-variant)',
        primary:                     'var(--color-primary)',
        'on-primary':                'var(--color-on-primary)',
        'primary-container':         'var(--color-primary-container)',
        'on-primary-container':      'var(--color-on-primary-container)',
        'primary-fixed':             'var(--color-primary-fixed)',
        'primary-fixed-dim':         'var(--color-primary-fixed-dim)',
        'on-primary-fixed':          'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant':  'var(--color-on-primary-fixed-variant)',
        'inverse-primary':           'var(--color-inverse-primary)',
        secondary:                   'var(--color-secondary)',
        'on-secondary':              'var(--color-on-secondary)',
        'secondary-container':       'var(--color-secondary-container)',
        'on-secondary-container':    'var(--color-on-secondary-container)',
        'secondary-fixed':           'var(--color-secondary-fixed)',
        'secondary-fixed-dim':       'var(--color-secondary-fixed-dim)',
        'on-secondary-fixed':        'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant':'var(--color-on-secondary-fixed-variant)',
        tertiary:                    'var(--color-tertiary)',
        'on-tertiary':               'var(--color-on-tertiary)',
        'tertiary-container':        'var(--color-tertiary-container)',
        'on-tertiary-container':     'var(--color-on-tertiary-container)',
        'tertiary-fixed':            'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim':        'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed':         'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        error:                       'var(--color-error)',
        'on-error':                  'var(--color-on-error)',
        'error-container':           'var(--color-error-container)',
        'on-error-container':        'var(--color-on-error-container)',
        'inverse-surface':           'var(--color-inverse-surface)',
        'inverse-on-surface':        'var(--color-inverse-on-surface)',
        'surface-tint':              'var(--color-surface-tint)',
      },
      borderRadius: {
        DEFAULT: '0px', lg: '0px', xl: '0px', full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'container-max': '1280px',
        gutter: '24px',
        unit: '4px',
        'margin-desktop': '80px',
      },
      fontFamily: {
        'headline-md':        ['Plus Jakarta Sans'],
        'display-lg-mobile':  ['Plus Jakarta Sans'],
        'display-lg':         ['Plus Jakarta Sans'],
        'badge-txt':          ['Inter'],
        'body-lg':            ['Plus Jakarta Sans'],
        'label-sm':           ['JetBrains Mono'],
        'body-md':            ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'display-lg':        ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'badge-txt':         ['11px', { lineHeight: '12px', fontWeight: '700' }],
        'body-lg':           ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'label-sm':          ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md':           ['16px', { lineHeight: '24px', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
